# Generated by Django 4.1 on 2023-04-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_no', models.AutoField(primary_key=True, serialize=False)),
                ('pos_no', models.IntegerField()),
                ('car_name', models.CharField(max_length=100)),
                ('car_brand', models.CharField(max_length=50)),
                ('car_plate', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=30)),
                ('car_meter', models.IntegerField()),
                ('car_price', models.IntegerField()),
                ('car_status', models.CharField(max_length=20)),
                ('car_contents', models.TextField()),
                ('car_created_at', models.DateTimeField(auto_now_add=True)),
                ('car_updated_at', models.DateTimeField(auto_now=True)),
                ('car_activate', models.BooleanField(default=True)),
            ],
        ),
    ]
