# Generated by Django 4.1 on 2023-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=50)),
                ('user_zip', models.IntegerField(max_length=11)),
                ('user_address', models.TextField()),
                ('user_detail_address', models.TextField()),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_updated_at', models.DateTimeField(auto_now=True)),
                ('user_disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
