# Generated by Django 4.1 on 2023-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_zip',
            field=models.IntegerField(),
        ),
    ]
