# Generated by Django 4.1 on 2023-04-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_no', models.AutoField(primary_key=True, serialize=False)),
                ('car_no', models.IntegerField()),
                ('user_no', models.IntegerField()),
                ('reserve_total_price', models.IntegerField()),
                ('reserve_status', models.CharField(default='예약중', max_length=15)),
                ('reserve_start_date', models.DateTimeField()),
                ('reserve_end_date', models.DateTimeField()),
                ('reserve_start_zone', models.IntegerField()),
                ('reserve_end_zone', models.IntegerField(null=True)),
                ('reserve_excess_cost', models.IntegerField(default=0)),
                ('reserve_accident_status', models.BooleanField(default=False)),
                ('reserve_created_at', models.DateTimeField(auto_now_add=True)),
                ('reserve_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
